# Schema for the configuration files of the Toggle Editable Field module.
field.formatter.settings.toggle_editable_formatter:
  type: mapping
  label: 'Toggle Editable Formatter'
  mapping:
    on:
      type: string
      label: 'Use custom label for On state'
    off:
      type: string
      label: 'Use custom label for Off state'
    size:
      type: string
      label: 'Size of toggle button'
    onstyle:
      type: string
      label: 'On state style of toggle button'
    offstyle:
      type: string
      label: 'Off state style of toggle button'
    height:
      type: integer
      label: 'Override height of toggle button'
    width:
      type: integer
      label: 'Override width of toggle button'
