name: spacedirectory
recipe: drupal8
proxy:
  mailhog:
    - mail.lemp.lndo.site
services:
  appserver:
    xdebug: true
    overrides:
      environment:
        # Support debugging Drush with XDEBUG. Use lando drush to debug.
        PHP_IDE_CONFIG: "serverName=appserver"
        BEHAT_PARAMS: >-
          {"extensions":{"Behat\\MinkExtension":{"base_url":"http://nginx/"},"Drupal\\DrupalExtension":{"drush":{"root":"/app/web"}}}}
  mailhog:
    type: mailhog
    hogfrom:
      - appserver    
    portforward: 1026    
tooling:
  phplint:
    service: appserver
    cmd: /app/vendor/bin/phplint
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat
config:
  via: nginx
  webroot: web
  database: mariadb:10.1
  drush: path:/app/vendor/bin/drush
