<?php

/**
 * @file
 * Contains spacebase_resources.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function spacebase_resources_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spacebase_resources module.
    case 'help.page.spacebase_resources':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Resource functionality for Spacebase.') . '</p>';
      return $output;

    default:
  }
}



/**
 * Implements hook_node_insert().
 *
 * When new content is created, queue the node in order to email
 * the appropriate Admins (Organization or Site) on next cron.
 *
 */

function spacebase_resources_node_insert(NodeInterface $node) {

   if ($node->getType() == 'resources') {
     $module = 'spacebase_resources';
     $key = 'new_content_resources';
     spacebase_core_queue_content_notifications($module, $key, $node);
   }
}



/**
 * Implements hook_mail_edit_keys().
 * Make it available to mail_edit to edit the template
 */
function spacebase_resources_mail_edit_templates() {
  return [
    'spacebase_resources.emails' => [
      'new_content_resources_org' => t('Org admins notice: Resource created in Org.'),
      'new_content_resources' => t('Site admins notice: Resource created.'),
    ],
  ];
}


