<?php

/**
 * @file
 * Contains spacebase_news.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;



/**
 * Implements hook_help().
 */
function spacebase_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spacebase_news module.
    case 'help.page.spacebase_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('News functionality for Spacebase') . '</p>';
      return $output;

    default:
  }
}



/**
 * Implements hook_node_insert().
 *
 * When new content is created, queue the node in order to email
 * the appropriate Admins (Organization or Site) on next cron.
 *
 */

function spacebase_news_node_insert(NodeInterface $node) {

  if ($node->getType() == 'sb_news_article') {
    $module = 'spacebase_news';
    $key = 'new_content_news';
    spacebase_core_queue_content_notifications($module, $key, $node);
  }
}






/**
 * Implements hook_mail_edit_keys().
 * Make it available to mail_edit to edit the template
 */
function spacebase_news_mail_edit_templates() {
  return [
    'spacebase_news.emails' => [
      'new_content_news_org' => t('Org admins notice: News article content created in Org.'),
      'new_content_news' => t('Site admins notice: News article content created.'),
    ],
  ];
}
