<?php

/**
 * @file
 * Contains spacebase_videos.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;


/**
 * Implements hook_help().
 */
function spacebase_videos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spacebase_videos module.
    case 'help.page.spacebase_videos':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Video functionality for Spacebase') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_node_insert().
 *
 * When new content is created, queue the node in order to email
 * the appropriate Admins (Organization or Site) on next cron.
 *
 */

function spacebase_videos_node_insert(NodeInterface $node) {

  if ($node->getType() == 'sb_video') {
    $module = 'spacebase_videos';
    $key = 'new_content_videos';
    spacebase_core_queue_content_notifications($module, $key, $node);
  }
}



/**
 * Implements hook_mail_edit_keys().
 * Make it available to mail_edit to edit the template
 */
function spacebase_videos_mail_edit_templates() {
  return [
    'spacebase_videos.emails' => [
      'new_content_videos_org' => t('Org admins notice: Video created in Org.'),
      'new_content_videos' => t('Site admins notice: Video created.'),
    ],
  ];
}

