# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true

      # Base the cache on the session cookie. Ignore all other cookies.
      cookies: ['/^SS?ESS/']

"https://spacebase.co/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true

      # Base the cache on the session cookie. Ignore all other cookies.
      cookies: ['/^SS?ESS/']

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"https://beta.{default}/":
    type: redirect
    to: "https://{default}/"

# Redirect all non-https connections to the equivalent https one.
"http://{default}/":
  type: redirect
  to: "https://{default}/"

"http://spacebase.co/":
  type: redirect
  to: "https://spacebase.co/"

"http://www.{default}/":
  type: redirect
  to: "https://{default}/"

"http://beta.{default}/":
  type: redirect
  to: "https://{default}/"
