<?php

/**
 * @file
 * Contains spacebase_orgs.module.
 */

use Drupal\Component\Render\PlainTextOutput;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter()
 */
function spacebase_orgs_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'group_organization_group_add_form') {
    $form['actions']['submit']['#value'] = t('Create Organization');
  }
}


function spacebase_orgs_send_email($key, $params) {
  $account = $params['account'];
  $site_mail = \Drupal::config('system.site')->get('mail_notification');
  if (empty($site_mail)) {
    $site_mail = \Drupal::config('system.site')->get('mail');
  }
  if (empty($site_mail)) {
    $site_mail = ini_get('sendmail_from');
  }
  $mail = \Drupal::service('plugin.manager.mail')->mail('spacebase_orgs', $key, $account->getEmail(), $account->getPreferredLangcode(), $params, $site_mail);
}

/**
 * Implements hook_mail().
 */
function spacebase_orgs_mail($key, &$message, $params) {
  $token_service = \Drupal::token();
  $language_manager = \Drupal::languageManager();
  $langcode = $message['langcode'];
  $variables = ['user' => $params['account'], 'group' => $params['group']];

  $language = $language_manager->getLanguage($params['account']->getPreferredLangcode());
  $original_language = $language_manager->getConfigOverrideLanguage();
  $language_manager->setConfigOverrideLanguage($language);
  $mail_config = \Drupal::config('spacebase_orgs.mail');

  $token_options = ['langcode' => $langcode, 'clear' => TRUE];
  $message['subject'] .= PlainTextOutput::renderFromHtml($token_service->replace($mail_config->get($key . '.subject'), $variables, $token_options));
  $message['body'][] = $token_service->replace($mail_config->get($key . '.body'), $variables, $token_options);

  $language_manager->setConfigOverrideLanguage($original_language);
}

function spacebase_orgs_theme($existing, $type, $theme, $path) {
  return [
    'org_pending_members_form' => [
      'render element' => 'form',
    ],
  ];
}
